default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new dev version to the Firebase App Distribution"
  lane :distribute do
    gradle(
      task: "clean assemble",
      flavor: "dev",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )

    commit = last_git_commit
    git_commit = commit[:message]

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID_ANDROID'],
      testers: ENV['APP_TESTERS'],
      release_notes: git_commit
    )
  end
end
